#!/bin/sh

# CHAPTERS=chap1,chap2,biblio
CHAPTERS=all

echo $CHAPTERS | latex main.tex
bibtex main.aux
echo $CHAPTERS | latex main.tex
echo $CHAPTERS | latex main.tex
dvips -Ppdf main.dvi
ps2pdf main.ps main.pdf
